from sqlalchemy import Column, String, DateTime, Text, Integer, Float, ForeignKey, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import ARRAY
from src.database import Base
import uuid


class QueryLog(Base):
    __tablename__ = "queries"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    book_id = Column(UUID(as_uuid=True), ForeignKey("books.id", ondelete="CASCADE"), nullable=False)
    mode = Column(String(20), nullable=False)  # 'full-book' or 'selected-text'
    question = Column(Text, nullable=False)
    selected_text = Column(Text)  # User-highlighted text (for selected-text mode)
    retrieved_chunk_ids = Column(ARRAY(UUID(as_uuid=True)))  # List of chunk IDs that were retrieved
    answer = Column(Text)  # The answer generated by the system
    latency = Column(Float)  # Query processing time in seconds
    tokens_used = Column(Integer)  # Number of tokens consumed in the query
    confidence_score = Column(Float)  # Confidence score of the generated answer
    user_id = Column(String(100))  # User ID for analytics
    session_id = Column(String(100))  # Session ID for conversation tracking
    is_successful = Column(Boolean, default=True)  # Whether the query was successful
    feedback_score = Column(Integer)  # User feedback score (1-5)
    feedback_comment = Column(Text)  # User feedback comment
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())